version: "3.8"
services:
  feed-parser:
    build:
      context: ./feed-parser-service
    ports:
      - "8010:8000"
    volumes:
      - ./feed-parser-service:/var/www
    depends_on:
      - mysql
  feed-transformer:
    build:
      context: ./feed-transformer-service
    ports:
      - "8011:8000"
    volumes:
      - ./feed-transformer-service:/var/www
    depends_on:
      - mysql
  data-processor:
    build:
      context: ./data-processor-service
    ports:
      - "8012:8000"
    volumes:
      - ./data-processor-service:/var/www
    depends_on:
      - mysql
  feed-fetcher:
    build:
      context: ./feed-fetcher-service
    ports:
      - "8013:8000"
    volumes:
      - ./feed-fetcher-service:/var/www
  reverb:
    build:
      context: ./reverb-service
    ports:
      - "6001:8000"
    volumes:
      - ./reverb-service:/var/www
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    ports:
      - "33066:3306"
    environment:
      MYSQL_DATABASE: parser_db
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: